In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray', arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')

In [9]:
arr2 = arr

In [10]:
np.savez('ziparray.npz',x=arr1, y=arr2)

In [11]:
array_archive = np.load('ziparray.npz')

In [13]:
array_archive['x']

array([0, 1, 2, 3, 4])

In [14]:
array_archive['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.savetxt('textarray.txt',arr,delimiter=',')

In [19]:
arr = np.loadtxt('textarray.txt', delimiter=',')

In [20]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])