In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
df1=DataFrame(np.random.randn(4,3),columns=['x','y','z'])
df2=DataFrame(np.random.randn(3,3),columns=['y','q','x'])

In [13]:
df1

x         y         z
0  0.440869 -0.789248 -0.876621
1  2.427742 -0.082373 -1.428718
2  0.309527  0.101915 -1.252969
3 -0.125927  0.480959  1.053134

In [14]:
df2

y         q         x
0 -0.186942  0.629238 -2.242697
1 -0.552050 -0.452310 -0.895635
2 -0.475950  0.645521 -1.850481

In [15]:
pd.concat([df1,df2])

q         x         y         z
0       NaN  0.440869 -0.789248 -0.876621
1       NaN  2.427742 -0.082373 -1.428718
2       NaN  0.309527  0.101915 -1.252969
3       NaN -0.125927  0.480959  1.053134
0  0.629238 -2.242697 -0.186942       NaN
1 -0.452310 -0.895635 -0.552050       NaN
2  0.645521 -1.850481 -0.475950       NaN

In [16]:
pd.concat([df1,df2],ignore_index=True)

q         x         y         z
0       NaN  0.440869 -0.789248 -0.876621
1       NaN  2.427742 -0.082373 -1.428718
2       NaN  0.309527  0.101915 -1.252969
3       NaN -0.125927  0.480959  1.053134
4  0.629238 -2.242697 -0.186942       NaN
5 -0.452310 -0.895635 -0.552050       NaN
6  0.645521 -1.850481 -0.475950       NaN