In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-2.18349784, -0.38605144, -0.19337782, -1.04353033,  0.80680512,
        1.09368045, -0.3604181 , -0.07938594,  0.81027129, -0.37401337])

In [7]:
B = np.random.randn(10)
B

array([-0.80523911, -0.18768527, -0.58836904, -0.24476517,  1.18409064,
        1.18261387, -0.13990534, -1.65822732, -0.66467316, -1.82545727])

In [8]:
# Binary Functions
np.add(A,B)

array([-2.98873696, -0.57373672, -0.78174685, -1.28829551,  1.99089575,
        2.27629432, -0.50032344, -1.73761325,  0.14559814, -2.19947065])

In [9]:
np.maximum(A,B)

array([-0.80523911, -0.18768527, -0.19337782, -0.24476517,  1.18409064,
        1.18261387, -0.13990534, -0.07938594,  0.81027129, -0.37401337])